export default {
  ru: {
    searchTitle: 'Поиск города',
    title: 'Погода в городе',
    wind: 'Ветер',
    cloudiness: 'Облачность',
    pressure: 'Давление',
    humidity: 'Влажность воздуха',
    sunrise: 'Восход солнца',
    sunset: 'Закат',
    windSpeed: 'м/с',
    feels_like: 'ощущается как',
    daily: 'Прогноз на неделю',
    hourly: 'Прогноз на 48 часов',
    clouds: 'Облачность',
    mercury: 'мм рт. ст.',
    location: 'Текущее расположение',
    searchError: 'Поздравляем! Вы нашли город о котором не знаем даже мы!',
    archive: 'Архив',
    archiveQuery: 'Архив запросов',
    archiveEmpty: 'Вы ещё не искали погоду, зайдите сюда позднее!',
    backToSearch: 'Назад к поиску',
    sortOnesFirst: 'Сначала новые',
    sortOnesOld: 'Сначала старые',
  },
  en: {
    searchTitle: 'Your city name',
    title: 'Weather in',
    wind: 'Wind',
    cloudiness: 'Cloudiness',
    pressure: 'Pressure',
    humidity: 'Humidity',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    windSpeed: 'm/s',
    feels_like: 'feels like',
    daily: 'Daily forecast',
    hourly: 'Forecast for 48 hours',
    clouds: 'clouds',
    mercury: 'mm of mercury',
    location: 'Current location',
    searchError: 'Congratulations! You\'ve found a city that even we don\'t know about!!',
    archive: 'Archive',
    archiveQuery: 'Request archive',
    archiveEmpty: 'You haven\'t searched for the weather yet!',
    backToSearch: 'Back to search',
    sortOnesFirst: 'New ones first',
    sortOnesOld: 'First the old ones',
  },
};
